// Generated by scripts/build-quick-estimate-apps-script.mjs. Do not edit.
"use strict";
var QuickEstimateWebApp = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // integrations/google-apps-script/quick-estimate/src/entrypoint.ts
  var entrypoint_exports = {};
  __export(entrypoint_exports, {
    doPost: () => doPost,
    setupQuickEstimateStorage: () => setupQuickEstimateStorage
  });

  // src/features/quick-estimate/constants/estimate-rule-set.ts
  var ESTIMATE_RULE_VERSION = "estimate-rule-2026-08-05";
  var ESTIMATE_BENCHMARK_VERSION = "incruit-2026-08-05";
  var ESTIMATE_RULE_SET = {
    version: ESTIMATE_RULE_VERSION,
    benchmarkVersion: ESTIMATE_BENCHMARK_VERSION,
    currency: "KRW",
    displayUnit: 1e4,
    maxDisplayAmount: 1e10,
    randomUpliftBps: {
      min: 100,
      max: 300
    },
    employeeCount: {
      min: 1,
      max: 6e3
    },
    industries: [
      {
        code: "software_it",
        label: "IT·소프트웨어",
        benchmarkRatePerEmployee: 118030,
        baseRatePerEmployee: 124e3
      },
      {
        code: "construction_engineering",
        label: "건설·엔지니어링",
        benchmarkRatePerEmployee: 1518670,
        baseRatePerEmployee: 1595e3
      },
      {
        code: "education_research",
        label: "교육·연구기관",
        benchmarkRatePerEmployee: 82640,
        baseRatePerEmployee: 87e3
      },
      {
        code: "finance_insurance",
        label: "금융·보험업",
        benchmarkRatePerEmployee: 358800,
        baseRatePerEmployee: 377e3
      },
      {
        code: "hospitality_other",
        label: "숙박·음식·기타 사업",
        benchmarkRatePerEmployee: 39760,
        baseRatePerEmployee: 42e3
      },
      {
        code: "transport_logistics",
        label: "운송·물류",
        benchmarkRatePerEmployee: 67190,
        baseRatePerEmployee: 71e3
      },
      {
        code: "agriculture_fisheries",
        label: "농림·수산업",
        benchmarkRatePerEmployee: 137810,
        baseRatePerEmployee: 145e3
      },
      {
        code: "real_estate_leasing",
        label: "부동산·임대",
        benchmarkRatePerEmployee: 317190,
        baseRatePerEmployee: 334e3
      },
      {
        code: "professional_services",
        label: "전문·사업지원 서비스",
        benchmarkRatePerEmployee: 171700,
        baseRatePerEmployee: 181e3
      },
      {
        code: "energy_utilities",
        label: "전기·가스·에너지",
        benchmarkRatePerEmployee: 121190,
        baseRatePerEmployee: 128e3
      },
      {
        code: "wholesale_retail",
        label: "도소매·유통",
        benchmarkRatePerEmployee: 78960,
        baseRatePerEmployee: 83e3
      },
      {
        code: "health_socialcare",
        label: "의료·사회복지",
        benchmarkRatePerEmployee: 631040,
        baseRatePerEmployee: 663e3
      },
      {
        code: "industrial_manufacturing",
        label: "제조·자동차·반도체",
        benchmarkRatePerEmployee: 101430,
        baseRatePerEmployee: 107e3
      },
      {
        code: "publishing_media",
        label: "출판·미디어",
        benchmarkRatePerEmployee: 80790,
        baseRatePerEmployee: 85e3
      }
    ]
  };

  // src/features/quick-estimate/constants/lead-submission-contract.ts
  var PRIVACY_NOTICE_VERSION = "privacy-2026-08-06-v1";
  var MARKETING_CONSENT_VERSION = "marketing-2026-08-06-v1";
  var SUBMISSION_PAYLOAD_MAX_BYTES = 16 * 1024;
  var MIN_SUBMISSION_ELAPSED_MS = 3e3;
  var MAX_SUBMISSION_ELAPSED_MS = 2 * 60 * 60 * 1e3;

  // src/features/quick-estimate/lib/calculate-estimate.ts
  function roundToNearestUnit(amount, unit) {
    return Math.round(amount / unit) * unit;
  }
  function roundUpToUnit(amount, unit) {
    return Math.ceil(amount / unit) * unit;
  }
  function calculateEstimate(input) {
    const industry = ESTIMATE_RULE_SET.industries.find(({ code }) => code === input.industryCode);
    if (industry === void 0) {
      return { status: "unsupported", reason: "unsupported_industry" };
    }
    if (!Number.isInteger(input.employeeCount)) {
      return { status: "invalid", reason: "employee_count_not_integer" };
    }
    if (input.employeeCount < ESTIMATE_RULE_SET.employeeCount.min || input.employeeCount > ESTIMATE_RULE_SET.employeeCount.max) {
      return { status: "invalid", reason: "employee_count_out_of_range" };
    }
    if (!Number.isInteger(input.randomUpliftBps)) {
      return { status: "invalid", reason: "random_uplift_not_integer" };
    }
    if (input.randomUpliftBps < ESTIMATE_RULE_SET.randomUpliftBps.min || input.randomUpliftBps > ESTIMATE_RULE_SET.randomUpliftBps.max) {
      return { status: "invalid", reason: "random_uplift_out_of_range" };
    }
    const benchmarkAmount = roundToNearestUnit(
      industry.benchmarkRatePerEmployee * input.employeeCount,
      ESTIMATE_RULE_SET.displayUnit
    );
    const upliftedAmount = industry.baseRatePerEmployee * input.employeeCount * (1e4 + input.randomUpliftBps) / 1e4;
    const candidateAmount = roundUpToUnit(upliftedAmount, ESTIMATE_RULE_SET.displayUnit);
    const amount = Math.max(candidateAmount, benchmarkAmount + ESTIMATE_RULE_SET.displayUnit);
    if (amount > ESTIMATE_RULE_SET.maxDisplayAmount) {
      return { status: "invalid", reason: "amount_limit_exceeded" };
    }
    return {
      status: "calculated",
      industryCode: industry.code,
      employeeCount: input.employeeCount,
      amount,
      currency: ESTIMATE_RULE_SET.currency,
      randomUpliftBps: input.randomUpliftBps,
      ruleVersion: ESTIMATE_RULE_SET.version,
      benchmarkVersion: ESTIMATE_RULE_SET.benchmarkVersion
    };
  }

  // src/features/quick-estimate/lib/generate-random-uplift.ts
  var UINT32_RANGE = 2 ** 32;

  // integrations/google-apps-script/quick-estimate/src/sheet-schema.ts
  var LEAD_SHEET_HEADERS = [
    "lead_id",
    "request_id",
    "submitted_at",
    "industry_code",
    "employee_count",
    "estimate_amount_krw",
    "random_uplift_bps",
    "estimate_rule_version",
    "benchmark_version",
    "company_name",
    "contact_name",
    "email",
    "phone",
    "privacy_basis",
    "privacy_notice_version",
    "privacy_agreed",
    "privacy_accepted_at",
    "marketing_agreed",
    "marketing_channels",
    "marketing_consent_version",
    "marketing_accepted_at",
    "source_path",
    "lead_status",
    "handled_at"
  ];
  var LEAD_STATUSES = ["NEW", "CONTACTING", "COMPLETED", "CLOSED"];
  var LEAD_SHEET_COLUMN_DESCRIPTIONS = [
    "Apps Script가 생성하는 내부 리드 식별자",
    "브라우저가 생성하고 재시도에서 유지하는 중복 방지 식별자",
    "Apps Script 서버 기준 UTC ISO 접수 시각",
    "견적 계산 업종 코드",
    "견적 계산 사원 수",
    "사용자에게 표시한 원 단위 예상 금액",
    "견적 계산에 사용한 basis point 난수",
    "견적 계산 규칙 버전",
    "외부 기준 snapshot 버전",
    "회사명",
    "담당자 이름",
    "상담 연락 이메일",
    "숫자로 정규화한 상담 연락 전화번호",
    "개인정보 처리 법적 근거 코드",
    "개인정보 수집·이용 고지 버전",
    "필수 개인정보 수집·이용 동의값",
    "Apps Script 서버 기준 개인정보 동의 시각",
    "선택 마케팅 활용 동의값",
    "EMAIL,SMS 중 동의한 마케팅 채널",
    "선택 마케팅 활용 동의 버전",
    "동의한 경우의 Apps Script 서버 기준 마케팅 동의 시각",
    "승인된 유입 경로",
    "NEW, CONTACTING, COMPLETED, CLOSED 중 운영 상태",
    "담당자가 최초 처리를 시작한 UTC ISO 시각"
  ];

  // integrations/google-apps-script/quick-estimate/src/apps-script-storage.ts
  var SPREADSHEET_ID_PROPERTY = "QUICK_ESTIMATE_SPREADSHEET_ID";
  var LEADS_SHEET_NAME = "leads";
  var CODEBOOK_SHEET_NAME = "codebook";
  var LOCK_TIMEOUT_MILLISECONDS = 5e3;
  var PHONE_COLUMN_NUMBER = 13;
  var PLAIN_TEXT_NUMBER_FORMAT = "@";
  function createAppsScriptLeadSheetStorage(dependencies) {
    return {
      withLock: (operation) => {
        const lock = dependencies.getScriptLock();
        if (!lock.tryLock(LOCK_TIMEOUT_MILLISECONDS)) {
          throw new Error("script_lock_unavailable");
        }
        try {
          return operation();
        } finally {
          lock.releaseLock();
        }
      },
      findLeadIdByRequestId: (requestId) => {
        const sheet = dependencies.getLeadsSheet();
        const lastRow = sheet.getLastRow();
        if (lastRow <= 1) {
          return null;
        }
        const rows = sheet.getRange(2, 1, lastRow - 1, 2).getDisplayValues();
        const matchedRow = rows.find((row) => row[1] === requestId);
        return (matchedRow == null ? void 0 : matchedRow[0]) || null;
      },
      appendLeadRow: (row) => {
        const sheet = dependencies.getLeadsSheet();
        const nextRow = Math.max(sheet.getLastRow() + 1, 2);
        sheet.getRange(nextRow, PHONE_COLUMN_NUMBER, 1, 1).setNumberFormat(PLAIN_TEXT_NUMBER_FORMAT);
        sheet.getRange(nextRow, 1, 1, LEAD_SHEET_HEADERS.length).setValues([Array.from(row)]);
      }
    };
  }
  function getRuntimeLeadsSheet() {
    const spreadsheetId = PropertiesService.getScriptProperties().getProperty(SPREADSHEET_ID_PROPERTY);
    if (spreadsheetId === null) {
      throw new Error("spreadsheet_id_not_configured");
    }
    const sheet = SpreadsheetApp.openById(spreadsheetId).getSheetByName(LEADS_SHEET_NAME);
    if (sheet === null) {
      throw new Error("leads_sheet_not_found");
    }
    return sheet;
  }
  function createRuntimeLeadSheetStorage() {
    return createAppsScriptLeadSheetStorage({
      getScriptLock: () => LockService.getScriptLock(),
      getLeadsSheet: getRuntimeLeadsSheet
    });
  }
  function createCodebookRows() {
    const columnRows = LEAD_SHEET_HEADERS.map((header, index) => {
      var _a;
      return [
        "column",
        header,
        (_a = LEAD_SHEET_COLUMN_DESCRIPTIONS[index]) != null ? _a : ""
      ];
    });
    const statusRows = LEAD_STATUSES.map((status) => ["lead_status", status, "허용 운영 상태"]);
    return [
      ["category", "code", "description"],
      ...columnRows,
      ...statusRows,
      ["privacy_notice_version", PRIVACY_NOTICE_VERSION, "현재 개인정보 수집·이용 고지 버전"],
      ["marketing_consent_version", MARKETING_CONSENT_VERSION, "현재 선택 마케팅 활용 동의 버전"],
      ["retention", "P1Y", "접수일로부터 1년 보유 후 월 1회 파기 대상 확인"]
    ];
  }
  function initializeSpreadsheet(spreadsheet) {
    var _a, _b;
    const leadsSheet = spreadsheet.getSheets()[0];
    if (leadsSheet === void 0) {
      throw new Error("default_sheet_not_found");
    }
    leadsSheet.setName(LEADS_SHEET_NAME);
    leadsSheet.getRange(1, 1, 1, LEAD_SHEET_HEADERS.length).setValues([Array.from(LEAD_SHEET_HEADERS)]);
    leadsSheet.setFrozenRows(1);
    leadsSheet.getRange(1, 1, 1, LEAD_SHEET_HEADERS.length).protect().setDescription("Apps Script 관리 header").setWarningOnly(false);
    const statusValidation = SpreadsheetApp.newDataValidation().requireValueInList(Array.from(LEAD_STATUSES), true).setAllowInvalid(false).build();
    leadsSheet.getRange(2, 23, leadsSheet.getMaxRows() - 1, 1).setDataValidation(statusValidation);
    leadsSheet.getRange(2, PHONE_COLUMN_NUMBER, leadsSheet.getMaxRows() - 1, 1).setNumberFormat(PLAIN_TEXT_NUMBER_FORMAT);
    const codebookSheet = spreadsheet.insertSheet(CODEBOOK_SHEET_NAME);
    const codebookRows = createCodebookRows();
    codebookSheet.getRange(1, 1, codebookRows.length, (_b = (_a = codebookRows[0]) == null ? void 0 : _a.length) != null ? _b : 3).setValues(codebookRows);
    codebookSheet.setFrozenRows(1);
    codebookSheet.autoResizeColumns(1, 3);
    SpreadsheetApp.flush();
  }
  function setupQuickEstimateStorage() {
    const properties = PropertiesService.getScriptProperties();
    const existingSpreadsheetId = properties.getProperty(SPREADSHEET_ID_PROPERTY);
    if (existingSpreadsheetId !== null) {
      const existingSpreadsheet = SpreadsheetApp.openById(existingSpreadsheetId);
      return {
        created: false,
        spreadsheetId: existingSpreadsheet.getId(),
        spreadsheetUrl: existingSpreadsheet.getUrl()
      };
    }
    const spreadsheet = SpreadsheetApp.create("간단 견적 리드 저장소");
    initializeSpreadsheet(spreadsheet);
    properties.setProperty(SPREADSHEET_ID_PROPERTY, spreadsheet.getId());
    return {
      created: true,
      spreadsheetId: spreadsheet.getId(),
      spreadsheetUrl: spreadsheet.getUrl()
    };
  }

  // integrations/google-apps-script/quick-estimate/src/submission-rate-limit.ts
  var GLOBAL_MINUTE_LIMIT = 10;
  var GLOBAL_DAILY_LIMIT = 100;
  var CONTACT_HOURLY_LIMIT = 3;
  var MINUTE_CACHE_TTL_SECONDS = 120;
  var CONTACT_CACHE_TTL_SECONDS = 7200;
  var SEEN_REQUEST_CACHE_TTL_SECONDS = 21600;
  var DAILY_STATE_PROPERTY = "QUICK_ESTIMATE_DAILY_RATE_LIMIT";
  var LOCK_TIMEOUT_MILLISECONDS2 = 5e3;
  function formatUtcMinute(now) {
    return now.toISOString().slice(0, 16);
  }
  function formatUtcHour(now) {
    return now.toISOString().slice(0, 13);
  }
  function formatUtcDate(now) {
    return now.toISOString().slice(0, 10);
  }
  function parseCounter(value) {
    if (value === null) {
      return 0;
    }
    const count = Number(value);
    if (!Number.isSafeInteger(count) || count < 0) {
      throw new Error("invalid_rate_limit_counter");
    }
    return count;
  }
  function parseDailyCount(value, currentDate) {
    if (value === null) {
      return 0;
    }
    const parsed = JSON.parse(value);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed) || typeof parsed.date !== "string" || !Number.isSafeInteger(parsed.count) || parsed.count < 0) {
      throw new Error("invalid_daily_rate_limit_state");
    }
    const state = parsed;
    return state.date === currentDate ? state.count : 0;
  }
  function enforceSubmissionRateLimit(submission, dependencies) {
    return dependencies.port.withLock(() => {
      const seenRequestKey = `quick-estimate:seen:${submission.requestId}`;
      if (dependencies.port.getCache(seenRequestKey) !== null) {
        return { ok: true };
      }
      const now = dependencies.now();
      const currentDate = formatUtcDate(now);
      const contactHash = dependencies.port.hashContact(
        `${submission.lead.email.toLowerCase()}\0${submission.lead.phone}`
      );
      const minuteKey = `quick-estimate:minute:${formatUtcMinute(now)}`;
      const contactKey = `quick-estimate:contact:${formatUtcHour(now)}:${contactHash}`;
      const minuteCount = parseCounter(dependencies.port.getCache(minuteKey));
      const contactCount = parseCounter(dependencies.port.getCache(contactKey));
      const dailyCount = parseDailyCount(dependencies.port.getDailyState(), currentDate);
      if (minuteCount >= GLOBAL_MINUTE_LIMIT || dailyCount >= GLOBAL_DAILY_LIMIT || contactCount >= CONTACT_HOURLY_LIMIT) {
        return { ok: false, code: "RATE_LIMITED" };
      }
      dependencies.port.putCache(minuteKey, String(minuteCount + 1), MINUTE_CACHE_TTL_SECONDS);
      dependencies.port.putCache(contactKey, String(contactCount + 1), CONTACT_CACHE_TTL_SECONDS);
      dependencies.port.setDailyState(
        JSON.stringify({ date: currentDate, count: dailyCount + 1 })
      );
      dependencies.port.putCache(seenRequestKey, "1", SEEN_REQUEST_CACHE_TTL_SECONDS);
      return { ok: true };
    });
  }
  function bytesToHex(bytes) {
    return bytes.map((byte) => ((byte + 256) % 256).toString(16).padStart(2, "0")).join("");
  }
  function createRuntimeSubmissionRateLimitPort() {
    const cache = CacheService.getScriptCache();
    const properties = PropertiesService.getScriptProperties();
    return {
      withLock: (operation) => {
        const lock = LockService.getScriptLock();
        if (!lock.tryLock(LOCK_TIMEOUT_MILLISECONDS2)) {
          throw new Error("rate_limit_lock_unavailable");
        }
        try {
          return operation();
        } finally {
          lock.releaseLock();
        }
      },
      getCache: (key) => cache.get(key),
      putCache: (key, value, expirationInSeconds) => cache.put(key, value, expirationInSeconds),
      getDailyState: () => properties.getProperty(DAILY_STATE_PROPERTY),
      setDailyState: (value) => properties.setProperty(DAILY_STATE_PROPERTY, value),
      hashContact: (value) => bytesToHex(
        Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, value, Utilities.Charset.UTF_8)
      )
    };
  }

  // integrations/google-apps-script/quick-estimate/src/storage-service.ts
  var FORMULA_PREFIX_PATTERN = /^[=+\-@]/u;
  function escapeSpreadsheetCellText(value) {
    return FORMULA_PREFIX_PATTERN.test(value) ? `'${value}` : value;
  }
  function buildLeadSheetRow(submission, leadId, submittedAt) {
    const marketingAcceptedAt = submission.marketing.agreed ? submittedAt : "";
    const row = [
      leadId,
      submission.requestId,
      submittedAt,
      submission.estimate.industryCode,
      submission.estimate.employeeCount,
      submission.estimate.amount,
      submission.estimate.randomUpliftBps,
      submission.estimate.ruleVersion,
      submission.estimate.benchmarkVersion,
      escapeSpreadsheetCellText(submission.lead.companyName),
      escapeSpreadsheetCellText(submission.lead.contactName),
      escapeSpreadsheetCellText(submission.lead.email),
      submission.lead.phone,
      submission.privacy.basis,
      submission.privacy.noticeVersion,
      submission.privacy.agreed,
      submittedAt,
      submission.marketing.agreed,
      submission.marketing.channels.join(","),
      submission.marketing.consentVersion,
      marketingAcceptedAt,
      submission.sourcePath,
      "NEW",
      ""
    ];
    if (row.length !== LEAD_SHEET_HEADERS.length) {
      throw new Error("lead_sheet_schema_mismatch");
    }
    return row;
  }
  function storeLeadSubmission(submission, dependencies) {
    try {
      return dependencies.storage.withLock(() => {
        const existingLeadId = dependencies.storage.findLeadIdByRequestId(submission.requestId);
        if (existingLeadId !== null) {
          return {
            ok: true,
            leadId: existingLeadId,
            duplicate: true
          };
        }
        const leadId = dependencies.generateLeadId();
        const submittedAt = dependencies.now().toISOString();
        const row = buildLeadSheetRow(submission, leadId, submittedAt);
        dependencies.storage.appendLeadRow(row);
        return {
          ok: true,
          leadId,
          duplicate: false
        };
      });
    } catch {
      return {
        ok: false,
        code: "STORAGE_UNAVAILABLE"
      };
    }
  }

  // integrations/google-apps-script/quick-estimate/src/validate-submission.ts
  var ROOT_KEYS = [
    "requestId",
    "estimate",
    "lead",
    "privacy",
    "marketing",
    "antiSpam",
    "sourcePath"
  ];
  var ESTIMATE_KEYS = [
    "industryCode",
    "employeeCount",
    "amount",
    "currency",
    "randomUpliftBps",
    "ruleVersion",
    "benchmarkVersion"
  ];
  var LEAD_KEYS = ["companyName", "contactName", "email", "phone"];
  var PRIVACY_KEYS = ["basis", "noticeVersion", "agreed"];
  var MARKETING_KEYS = ["agreed", "channels", "consentVersion"];
  var ANTI_SPAM_KEYS = ["honeypot", "elapsedMs"];
  var CONTROL_CHARACTER_PATTERN = /[\u0000-\u001f\u007f-\u009f]/u;
  var EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/u;
  var PHONE_SEPARATOR_PATTERN = /[\s().-]/gu;
  var UUID_V4_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
  var MARKETING_CHANNELS = /* @__PURE__ */ new Set(["EMAIL", "SMS"]);
  function failure(code) {
    return { ok: false, code };
  }
  function isRecord(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
  }
  function hasExactKeys(value, expectedKeys) {
    const actualKeys = Object.keys(value);
    return actualKeys.length === expectedKeys.length && actualKeys.every((key) => expectedKeys.includes(key));
  }
  function calculateUtf8ByteLength(value) {
    let bytes = 0;
    for (const character of value) {
      const codePoint = character.codePointAt(0);
      if (codePoint === void 0) {
        continue;
      }
      if (codePoint <= 127) {
        bytes += 1;
      } else if (codePoint <= 2047) {
        bytes += 2;
      } else if (codePoint <= 65535) {
        bytes += 3;
      } else {
        bytes += 4;
      }
    }
    return bytes;
  }
  function normalizeRequiredText(value, maxLength) {
    if (typeof value !== "string") {
      return null;
    }
    const normalized = value.trim();
    if (normalized.length === 0 || normalized.length > maxLength || CONTROL_CHARACTER_PATTERN.test(normalized)) {
      return null;
    }
    return normalized;
  }
  function normalizeEmail(value) {
    const normalized = normalizeRequiredText(value, 254);
    if (normalized === null || !EMAIL_PATTERN.test(normalized)) {
      return null;
    }
    return normalized;
  }
  function normalizePhone(value) {
    var _a;
    const normalized = (_a = normalizeRequiredText(value, 30)) == null ? void 0 : _a.replace(PHONE_SEPARATOR_PATTERN, "");
    if (normalized === void 0 || !/^\d{9,11}$/u.test(normalized)) {
      return null;
    }
    return normalized;
  }
  function normalizeMarketingChannels(value) {
    if (!Array.isArray(value) || value.some((channel) => !MARKETING_CHANNELS.has(channel))) {
      return null;
    }
    const uniqueChannels = new Set(value);
    if (uniqueChannels.size !== value.length) {
      return null;
    }
    return ["EMAIL", "SMS"].filter(
      (channel) => uniqueChannels.has(channel)
    );
  }
  function validateParsedSubmission(input) {
    if (!isRecord(input) || !hasExactKeys(input, ROOT_KEYS)) {
      return failure("INVALID_INPUT");
    }
    const { estimate, lead, privacy, marketing, antiSpam } = input;
    if (!isRecord(estimate) || !hasExactKeys(estimate, ESTIMATE_KEYS) || !isRecord(lead) || !hasExactKeys(lead, LEAD_KEYS) || !isRecord(privacy) || !hasExactKeys(privacy, PRIVACY_KEYS) || !isRecord(marketing) || !hasExactKeys(marketing, MARKETING_KEYS) || !isRecord(antiSpam) || !hasExactKeys(antiSpam, ANTI_SPAM_KEYS)) {
      return failure("INVALID_INPUT");
    }
    if (estimate.ruleVersion !== ESTIMATE_RULE_VERSION || estimate.benchmarkVersion !== ESTIMATE_BENCHMARK_VERSION) {
      return failure("UNSUPPORTED_RULE");
    }
    const calculated = calculateEstimate({
      industryCode: typeof estimate.industryCode === "string" ? estimate.industryCode : "",
      employeeCount: typeof estimate.employeeCount === "number" ? estimate.employeeCount : NaN,
      randomUpliftBps: typeof estimate.randomUpliftBps === "number" ? estimate.randomUpliftBps : NaN
    });
    if (calculated.status === "unsupported") {
      return failure("UNSUPPORTED_RULE");
    }
    if (calculated.status !== "calculated" || estimate.amount !== calculated.amount || estimate.currency !== calculated.currency) {
      return failure("INVALID_INPUT");
    }
    if (privacy.basis !== "CONSENT" || privacy.noticeVersion !== PRIVACY_NOTICE_VERSION || privacy.agreed !== true) {
      return failure("INVALID_CONSENT");
    }
    if (antiSpam.honeypot !== "" || !Number.isInteger(antiSpam.elapsedMs) || antiSpam.elapsedMs < MIN_SUBMISSION_ELAPSED_MS || antiSpam.elapsedMs > MAX_SUBMISSION_ELAPSED_MS) {
      return failure("INVALID_INPUT");
    }
    const channels = normalizeMarketingChannels(marketing.channels);
    if (typeof marketing.agreed !== "boolean" || marketing.consentVersion !== MARKETING_CONSENT_VERSION || channels === null || marketing.agreed && channels.length === 0 || !marketing.agreed && channels.length > 0) {
      return failure("INVALID_CONSENT");
    }
    const companyName = normalizeRequiredText(lead.companyName, 100);
    const contactName = normalizeRequiredText(lead.contactName, 50);
    const email = normalizeEmail(lead.email);
    const phone = normalizePhone(lead.phone);
    if (!UUID_V4_PATTERN.test(typeof input.requestId === "string" ? input.requestId : "") || companyName === null || contactName === null || email === null || phone === null || input.sourcePath !== "/") {
      return failure("INVALID_INPUT");
    }
    const submission = {
      requestId: input.requestId,
      estimate: {
        industryCode: calculated.industryCode,
        employeeCount: calculated.employeeCount,
        amount: calculated.amount,
        currency: calculated.currency,
        randomUpliftBps: calculated.randomUpliftBps,
        ruleVersion: calculated.ruleVersion,
        benchmarkVersion: calculated.benchmarkVersion
      },
      lead: {
        companyName,
        contactName,
        email,
        phone
      },
      privacy: {
        basis: "CONSENT",
        noticeVersion: PRIVACY_NOTICE_VERSION,
        agreed: true
      },
      marketing: {
        agreed: marketing.agreed,
        channels,
        consentVersion: MARKETING_CONSENT_VERSION
      },
      antiSpam: {
        honeypot: "",
        elapsedMs: antiSpam.elapsedMs
      },
      sourcePath: "/"
    };
    return { ok: true, submission };
  }
  function parseAndValidateSubmissionPayload(payload) {
    if (typeof payload !== "string" || calculateUtf8ByteLength(payload) > SUBMISSION_PAYLOAD_MAX_BYTES) {
      return failure("INVALID_INPUT");
    }
    try {
      return validateParsedSubmission(JSON.parse(payload));
    } catch {
      return failure("INVALID_INPUT");
    }
  }

  // integrations/google-apps-script/quick-estimate/src/web-app.ts
  function logFailureSafely(dependencies, event) {
    try {
      dependencies.logFailure(event);
    } catch {
    }
  }
  function handleQuickEstimatePost(payload, dependencies) {
    const validation = parseAndValidateSubmissionPayload(payload);
    if (!validation.ok) {
      logFailureSafely(dependencies, {
        code: validation.code,
        occurredAt: dependencies.now().toISOString()
      });
      return validation;
    }
    const rateLimit = dependencies.enforceRateLimit(validation.submission);
    if (!rateLimit.ok) {
      logFailureSafely(dependencies, {
        code: rateLimit.code,
        occurredAt: dependencies.now().toISOString(),
        requestId: validation.submission.requestId
      });
      return rateLimit;
    }
    const result = dependencies.storeSubmission(validation.submission);
    if (!result.ok) {
      logFailureSafely(dependencies, {
        code: result.code,
        occurredAt: dependencies.now().toISOString(),
        requestId: validation.submission.requestId
      });
    }
    return result;
  }
  function createJsonOutput(response) {
    return ContentService.createTextOutput(JSON.stringify(response)).setMimeType(
      ContentService.MimeType.JSON
    );
  }
  function doPost(event) {
    try {
      const response = handleQuickEstimatePost(event == null ? void 0 : event.parameter.payload, {
        enforceRateLimit: (submission) => enforceSubmissionRateLimit(submission, {
          port: createRuntimeSubmissionRateLimitPort(),
          now: () => /* @__PURE__ */ new Date()
        }),
        storeSubmission: (submission) => storeLeadSubmission(submission, {
          storage: createRuntimeLeadSheetStorage(),
          generateLeadId: () => Utilities.getUuid(),
          now: () => /* @__PURE__ */ new Date()
        }),
        logFailure: (failure2) => console.error(JSON.stringify(failure2)),
        now: () => /* @__PURE__ */ new Date()
      });
      return createJsonOutput(response);
    } catch {
      const response = { ok: false, code: "INTERNAL_ERROR" };
      console.error(
        JSON.stringify({
          code: response.code,
          occurredAt: (/* @__PURE__ */ new Date()).toISOString()
        })
      );
      return createJsonOutput(response);
    }
  }
  return __toCommonJS(entrypoint_exports);
})();
function doPost(e) {
  return QuickEstimateWebApp.doPost(e);
}
function setupQuickEstimateStorage() {
  return QuickEstimateWebApp.setupQuickEstimateStorage();
}
